spring.application.name=Bank Loan

server.port=8090

camunda.client.mode=selfmanaged
camunda.client.enabled=true
camunda.client.auth.method=none
camunda.client.grpc-address=http://127.0.0.1:26500
camunda.client.rest-address=http://127.0.0.1:8080